docs/api/srfi/27.md
docs/api/srfi/9.md

Hi,
this patch adds rump documentation for srfi-9 and srfi-27 including an export list and a reference to the srfi document. This does not include the symbol next-mrg32k3a from srfi-27.
Regards, Mark

Rump documentation for srfi-9 and srfi-27

---

srfi/60.scm
srfi/60.sld

I use bitwise operations a lot, and not having these supported in Cyclone is a bit of a pain. So here's my first PR on the subject.
I have made somewhat limited use of ``define-c`` here - I believe I could do much more of this at a lower level, but decided I'd rather err on the side of caution. Feel free to optimize this.
On a related note - are there any tests for the SRFI libraries? All of them supply some use examples, which can be used as a basis for this. This is what Chibi does, and I would recommend we do it too, if possible.

Adding SRFI 60

---

Makefile

This is just cleanup - the result is 20 lines shorter, and much more amenable to (for example) parallel builds. It'll also hopefully require fewer modifications as Cyclone grows.
A few things I left (mostly) alone:
1. The makefiles in ``examples``, although I'll probably get to them later.
2. ``bootstrap`` target: I haven't touched this, because I wanted to confirm that it does what I think it does. I assume that this is what generates the code that now lives in cyclone-bootstrap, or am I missing something?
3. ``install`` target: This is something I plan to do later.
I removed a bunch of comments of old lines, as well as a rule to build a shared lib version of libcyclone, but I can restore them if you'd rather have them there than in the git history. I removed the latter mostly because it …

Makefile refactor

---

CHANGELOG.md
Makefile
srfi/28.scm
srfi/28.sld
tests/srfi-28-tests.scm
tests/srfi-60-tests.scm

This is quite a simple, but very useful, SRFI. There aren't many tests for it (only 2, as based on the [SRFI document][1]), but they all pass.
[1]: https://srfi.schemers.org/srfi-28/

Adding support for SRFI 28, with working tests

---

docs/API.md
docs/api/srfi/121.md
docs/api/srfi/18.md
docs/api/srfi/28.md
docs/api/srfi/60.md
docs/api/srfi/69.md
srfi/60.scm
srfi/60.sld

That should be the documentation done. It can probably do with some improving in the long run, though.
I've also added some code changes to SRFI 60, mostly based on heavier use of inline C, and the removal of any ``(scheme inexact)`` procedures. In the longer run, I suspect I'll probably end up rewriting the *whole thing* entirely in C, with Scheme wrappers to provide the expected API.

Documentation for new SRFIs, some small code changes

---

Makefile

Some explanation required -- I like to build cyclone-bootstrap with a different binary name, "cyclone-bootstrap", and then use it to build cyclone, but if the name `cyclone` is hardcoded instead of using `$(CYCLONE)`, the build fails.

Fix bootstrap

---

scheme/base.sld

R7RS states that there's three possible scenarios for read-string:
- More characters can be read than asked for (return string)
- Less characters can be read than asked for (return string)
- No characters can be read (return EOF)
This commit ensures the last scenario works as intended.

read-string: return EOF if nothing can be read

---

.travis.yml
Makefile.config

This PR adds CI testing on Linux with both Clang and GCC, and on macOS. The first commit adds the Travis configuration file for the builds and the second commit corrects a linker flag on macOS.
What you'll need to do is create an account associated with your GitHub profile on https://travis-ci.org, then once you're signed in, enable building on cyclone. Click the little gear to make any changes to the settings you'd like. I recommend enabling "Build only if .travis.yml is present" and keeping the other default settings.
Once it's enabled we might have to close and reopen this PR to force a build.
Fixes #163

Enable Travis for continuous integration testing

---

README.md

Just a small adjustment so that when you click on the badge, you're taken to the Travis site with the most recent build.

Make the Travis badge a link to Travis

---

scheme/cyclone/cgen.sld

A program as simple as the following:
(import (scheme base))
(if (system "ls")
1)
generates a compilation error:
$ cyclone -td test.scm
test.c: In function ‘c_entry_pt_first_lambda’:
test.c:327:1: error: expected ‘;’ before ‘}’ token
} else { 
^
The corresponding C code is (with manually corrected indentation):
static void c_entry_pt_first_lambda(void *data, int argc, closure cont, object value) {
make_utf8_string_with_len(c_735, "ls", 2, 2);
if( (boolean_f != Cyc_system(&c_735)) ){
__halt(obj_int2obj(1))    **<--- missing semi-colon**
} else { 
__halt(boolean_f);
} ;
;   **<--- extra semi-colon** (don't know why and where, still revising code)
}
Uncommenting ";\n" on line 358 the makes the code compile properly, although this line appends semi-colons to code that already have them. The …

Updated scheme/cyclone/cgen.sld to insert correct

---

scheme/cyclone/cgen.sld

Preserved only those preceded by commented code. 
BTW, Justin, could you please review if any of those commented code is still necessary? I'd really appreciate stripping them from the code.
Thanks!
Arthur

Moved trailing parens into correct position

---

scheme/cyclone/cgen.sld

I followed [Riastradh style rules](https://mumble.net/~campbell/scheme/style.txt) for updating comments.
Indentation of some lines where changed a bit and styling overhaul will be completed by the next pull request. Some lines had end whitespace trimmed. 
I didn't inlcude a single line of code, but I ran 'make test' and all tests passed.

Converted improper semi-colons into double ones (and vice-versa)

---

scheme/cyclone/cgen.sld

Justin, the previous pull request did not corrected the bug on '%halt' translation into '__halt(...)'. I changed the c:seralize procedure to check if the end of the compiled expression has a semi-colon at its end. If not, add one.
It works fine and passes all the tests (although this specific error doesn't is not catched up with 'make test'). 
I'm a bit worried about cgen.sld because it doesn't have a systematic way of emiting C code. It passes a parameter 'append-preamble' not used a single time. The term 'prefix' means indentation in one section but when dealing with macros it means a prefix to a variable name. The procedure I modified, 'c:serialize' is used 4 or 5 times and is not default. I thought about overhauling indentation procedures, but I'm not sure I'm skilled enough. If you …

Previous try to correct semi-colon bug failed

---

Makefile
Makefile.config

* Updates `Makefile` for [homebrew](https://brew.sh/) compatibility. cyclone can now build itself on macOS after cyclone-bootstrap has been run.
* None for non-macOS platforms.
* On macOS cyclone can now build itself after cyclone-bootstrap has been run.
* The compiler output is not as clean as linux– some warnings and notes are still produced. (`warning: shifting a negative signed value is undefined [-Wshift-negative-value]` and `note: expanded from macro`) – these can be cleaned up in another PR.
* `libtool` is used on macOS instead of `ar`
* Here are the homebrew formulas used for testing:
* [cyclone-bootstrap](https://github.com/adamfeuer/homebrew-cyclone/blob/master/cyclone-bootstrap.rb)
* [cyclone](https://github.com/adamfeuer/homebrew-cyclone/blob/master/cyclone.rb)
* `make; make …

Homebrew compatibility

---

README.md

- updated Mac install instructions for new homebrew-cyclone repo location in cyclone-scheme org

updated Mac install instructions for new homebrew-cyclone repo location in cyclone-scheme org

---

.travis.yml

CK git tags don't have a `v` prefix before the version number. The current Travis log says:
`error: pathspec 'v0.6.0' did not match any file(s) known to git`
* The build seems to pass anyway, even though it ends up using the latest CK version.
* The Travis config `before_install` section has many commands under one bullet point (the `git checkout` being one of them). If one of the sub-commands fails, the error doesn't propagate upwards to the build runner. Should probably have each command as its own bullet point whenever possible?

Fix Concurrency Kit version tag in Travis

---

Makefile

If hardcoded, 'make' will use native FreeBSD 'make' instead of 'gmake'.

Change 'make' into '$(MAKE)' for libtommath installation

---

icyc.scm

@justinethier, although the `-p` can handle multiple occurrences of sexps to evaluate, the following would occur, which does not seem an interesting behaviour to me:
```scheme
$ icyc -p "(define a 1) (display a)" 
ok  ;; evaluation of the first sexp - the second is explicitly ignored
```
The following also doesn't work, so we can conclude there is no continuity between sexps:
```scheme
$ icyc -p "(define a 1)" -p "(display a)" 
Error: Unbound variable: a 
Call history:
scheme/eval.sld:analyze-variable
scheme/base.sld:Cyc-map-loop-1
scheme/cyclone/util.sld:env:lookup-variable-value
scheme/cyclone/util.sld:env:_lookup-variable-value
scheme/base.sld:Cyc-map-loop-1
scheme/cyclone/util.sld:env:lookup-variable-value
scheme/cyclone/util.sld:env:_lookup-variable-value
scheme/base.sld:error …
```

Improved "-p" flag to read/evalute all sexp passed

---

CHANGELOG.md
docs/api/cyclone/foreign.md
libs/cyclone/foreign.sld

@justinethier, I couldn't make the new type named `void` probably due to a name clash with the `void` procedure itself. Is there a workaround? cvoid is not as elegant as `(cyclone foreign)` itself :)

Fixed '(cyclone foreign)' and added 'cvoid' type

---

scheme/base.sld

Hi there, I ran into a bug where I needed to branch on a procedure receiving either a record or a vector, and noticed that record type predicates don't check the length of the target before checking if the vector is actually a record so when my procedure received a vector with less than two entries it would crash when trying to access the record marker or record type name.
For example:
```scheme
(define-record-type <my-record> (my-record) my-record?)
(let ((v (vector)))
(if (my-record? v) #t #f))
```
would crash with
```
Error: vector-ref - invalid index: 0 
```
So I added a check to the procedure returned from `make-type-predicate` to verify that the vector has three entries.
Of course, there is still another problem in that the result of the following expression results in `#t` …

Fix a crash in record predicates

---

scheme/base.sld

They both should not return `#f`. The correct behavior is allowed due to the fix for #377.

Unless/when don't have alternate clause

---

scheme/repl.sld

On Unix-like operating systems stdio.h (which Cyclone seems to use
internally) is line-buffered. As such, the prompt will only be written
after a newline character is written (since the prompt itself doesn't
contain a newline) which is probably not what was
intended here. This commit fixes this issue by always flushing the
current-output-port after writing the prompt string.

Flush current-output-port after writing prompt to it

---

Makefile.config
Makefile.config.raspberry-pi-2

The [conditional variable assignment operator](https://www.gnu.org/software/make/manual/make.html#index-conditional-variable-assignment) in Makefiles (`?=`) will only assign a value if its not defined yet. However, CFLAGS/LDFLAGS are commonly defined as environment variables to pass custom compiler/linker flags (e.g. `-Os`). Unfortunately, Cyclone adds mandatory compiler flags (without which it doesn't compile) via the conditional variable assignment operator which is incorrect as these flags will not be added if CFLAGS/LDFLAGS is defined in the environment. This commit fixes this issue by appending flags to CFLAGS/LDFLAGS instead of using the conditional assignment operator.
This should also fix weird hacks such as this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cyclone-schem …

Don't use conditional assignment operator for CFLAGS/LDFLAGS

---

Makefile

Since commit 15a8f2cfe51bffa2844159cd267bd896a1c7ed46 the build order must be as follows:
1. Bootstrap cyclone.scm using a pre-existing compiler.
2. Using cyclone from the previous step, build all libraries.
3. Using the artifacts from the previous two steps, build icyc, examples, and tests.
This commit updates the Makefile prerequisites accordingly to reflect this change in build order. Otherwise, Cyclone does not correctly compile in parallel build mode with `-jN`.

Improve Makefile prerequisites

---

Makefile

Otherwise `make libs` cannot find `(cyclone test)`:
./cyclone -A . -COPT '-Iinclude' -CLNK '-L.' libs/cyclone/test.sld
Error: Unable to open file: "/usr/lib/cyclone/cyclone/test.scm"
make: *** [Makefile:170: libs/cyclone/test.o] Error
Testing Procedure:
1. Install a pre-compiled cyclone version globally (for `CYCLONE_SYSTEM`)
2. Run `make cyclone`
3. Uninstall the global cyclone version (should not be needed after this step)
4. Run `make libs` fails without this commit, should pass with it
5. Run `make icyc`

Makefile: Add `-A libs` to CYCLONE_LOCAL

---

Makefile.config
cyclone.scm

This commit separates include/library search directory options from "normal" compiler/linker options and places options passed via the `-COPT`/`-CLNK` command-line flags in-between. This allows overwriting the default search paths, since contrary to all other options, the search paths must be prepend for an `-I`/`-L` option to take precedence over an existing one.
To test this, compare the new concatenation of linker/compiler options for `test.scm` [with the previous one](https://github.com/justinethier/cyclone/issues/476#issuecomment-898884369):
```
$ ./cyclone -d -A . -COPT '-Iinclude' -CLNK '-L.' /tmp/test.scm
gcc /tmp/test.c  -O2 -Wall -Iinclude -I/usr/include -c -o /tmp/test.o
gcc /tmp/test.o  /usr/lib/cyclone/scheme/cyclone/common.o  /usr/lib/cyclone/scheme/base.o …
```

Allow prepending include/library search path through -COPT/-CLNK

---

Makefile.config

This is a follow up to https://github.com/justinethier/cyclone/pull/482#discussion_r758902860
The -I$(PREFIX)/include needs to be moved away from BASE_CFLAGS since,
otherwise, it will be added *before* `~cc-extra~` and thus (partially)
circumvent the changes from #482. Compare the following two Cyclone
invocations with/without this commit.
Without this commit:
$ ./cyclone -d -A . -A libs -COPT '-Iinclude' -CLNK '-L.' scheme/complex.sld
gcc scheme/complex.c […] -I/usr/include -Wl,--export-dynamic -Iinclude -L/usr/lib -c
With this commit applied:
$ ./cyclone -d -A . -A libs -COPT '-Iinclude' -CLNK '-L.' scheme/complex.sld
gcc scheme/complex.c […] -Wl,--export-dynamic -Iinclude -I/usr/include -c
In #482, I originally removed the -I$(PREFIX)/include from BASE_CFLAGS
entirely. However, back …

Makefile.config: Move -I$(PREFIX)/include from BASE_CFLAGS to CC_LIB

---

Makefile

Otherwise, the Cyclone compiler build from cyclone.scm using the
installed Cyclone version will use the libcyclone.a and libcyclonebn.a
file from /usr/lib instead of the one compiled as a prerequisite by
GNU make in the current directory.

Makefile: Also pass -L. for CYCLONE_SYSTEM

---

srfi/143.sld

In the SRFI text, these are constants:
```
fx-width
fx-greatest
fx-least
```
But they were implemented as procedures in Cyclone.
This patch changes that, so they now are implemented as constants.

SRFI 143: `fx-{width,least,greatest}` are not procedures

---

include/cyclone/runtime.h
runtime.c
scheme/base.sld
tests/base.scm

R7RS requires (round x) to round to even when x is halfway between two integers. The current implementation uses round() which rounds away from zero.
This pull request adds two tests for the half integer behavior, and an implementation that rounds to even for the half integer case.

Implement r7rs round to even behaviour for half integers

---

srfi/106.sld

This change defines `*ai-v4mapped*` to zero when `AI_V4MAPPED` is undefined and similarly for `*ai-all*` (similar to other patches). This allows (srfi 106) to be available on NetBSD and other platforms without `AI_V4MAPPED` and is the recommended behaviour by the author of SRFI-106:
https://srfi-email.schemers.org/srfi-106/msg/2762553/

Define *ai-v4mapped* to zero on platforms where AI_V4MAPPED is undefined

---

Makefile.config

GCC 14 has enabled various warnings as errors by default, e.g. -Wimplicit-function-declaration. This causes the current feature detection code for `open_memstream(3)` and `fmemopen(3)` to fail with GCC 14.
This commit restores compatibility with GCC 14 in this regard.
Note that it may also be beneficial to pass a feature test macro such as -D_POSIX_C_SOURCE. See the feature test macro requirements for open_memstream(3)` and `fmemopen(3)`.
See also https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/72328

Fix open_memstream/fmemopen feature detection with GCC >= 14

---

runtime.c
srfi/18.sld

According to SRFI-18, `pthread-terminate!` takes a thread-object as argument, whereas cyclone `pthread-terminate!` does not take any arguments.
The current implementation terminates the calling thread. This pull request uses `pthread_cancel` to request that the target thread terminates and that `Cyc_end_thread` is called from the target thread.
The case for the `*primordial-thread*` and calling thread being the same as the target thread are handled more or less according to the current implementation.

pthread-terminate! takes a thread object as argument

---

gc.c
include/cyclone/runtime.h
include/cyclone/types.h
runtime.c
srfi/18.sld

Work on garbage collection, related to issue #534.
When threads terminate, their heaps are merged with the primordial thread's heap. This triggers a minor GC.
Under certain conditions, a major GC will not be triggered and terminated thread's heap pages will nor be swept or freed which can lead to significant memory being used by a program.
These commits attempt to ensure that the heaps are swept and pages are freed when possible.
Some issues that still need to be resolved:
1. The primordial thread does too much work, should the thread which call `pthread-join!` do the work instead?
2. Threads which terminate by `thread-terminate!` are not handled correctly.
3. In the [comment on issue #534](https://github.com/justinethier/cyclone/issues/534#issuecomment-2571743790) the "context" logic …

Improve garbage collection for terminated threads
